include(${THIRD_PARTY_REPOS}/tbb/cmake/TBBGet.cmake)
include(${THIRD_PARTY_REPOS}/tbb/cmake/TBBBuild.cmake)
set(tbb_root ${THIRD_PARTY_REPOS}/tbb)
#tbb_get(TBB_ROOT tbb_root SOURCE_CODE)
tbb_build(TBB_ROOT ${tbb_root} CONFIG_DIR TBB_DIR)
#include_directories(${tbb_root}/include)
find_package(TBB REQUIRED)
message("Found TBB targets: ${TBB_IMPORTED_TARGETS}")
message("TBB Configuration at : ${TBB_DIR}")
