# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CarMotionData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CarMotionData.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x43\x61rMotionData.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\"\xce\x03\n\rCarMotionData\x12\x18\n\x10m_worldPositionX\x18\x01 \x01(\x02\x12\x18\n\x10m_worldPositionY\x18\x02 \x01(\x02\x12\x18\n\x10m_worldPositionZ\x18\x03 \x01(\x02\x12\x18\n\x10m_worldVelocityX\x18\x04 \x01(\x02\x12\x18\n\x10m_worldVelocityY\x18\x05 \x01(\x02\x12\x18\n\x10m_worldVelocityZ\x18\x06 \x01(\x02\x12\x1a\n\x12m_worldForwardDirX\x18\x07 \x01(\x11\x12\x1a\n\x12m_worldForwardDirY\x18\x08 \x01(\x11\x12\x1a\n\x12m_worldForwardDirZ\x18\t \x01(\x11\x12\x18\n\x10m_worldRightDirX\x18\n \x01(\x11\x12\x18\n\x10m_worldRightDirY\x18\x0b \x01(\x11\x12\x18\n\x10m_worldRightDirZ\x18\x0c \x01(\x11\x12\x17\n\x0fm_gForceLateral\x18\r \x01(\x02\x12\x1c\n\x14m_gForceLongitudinal\x18\x0e \x01(\x02\x12\x18\n\x10m_gForceVertical\x18\x0f \x01(\x02\x12\r\n\x05m_yaw\x18\x10 \x01(\x02\x12\x0f\n\x07m_pitch\x18\x11 \x01(\x02\x12\x0e\n\x06m_roll\x18\x12 \x01(\x02\x62\x06proto3')
)




_CARMOTIONDATA = _descriptor.Descriptor(
  name='CarMotionData',
  full_name='deepf1.twenty_eighteen.protobuf.CarMotionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_worldPositionX', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldPositionX', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldPositionY', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldPositionY', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldPositionZ', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldPositionZ', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldVelocityX', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldVelocityX', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldVelocityY', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldVelocityY', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldVelocityZ', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldVelocityZ', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldForwardDirX', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldForwardDirX', index=6,
      number=7, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldForwardDirY', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldForwardDirY', index=7,
      number=8, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldForwardDirZ', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldForwardDirZ', index=8,
      number=9, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldRightDirX', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldRightDirX', index=9,
      number=10, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldRightDirY', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldRightDirY', index=10,
      number=11, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_worldRightDirZ', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_worldRightDirZ', index=11,
      number=12, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_gForceLateral', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_gForceLateral', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_gForceLongitudinal', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_gForceLongitudinal', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_gForceVertical', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_gForceVertical', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_yaw', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_yaw', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_pitch', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_pitch', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_roll', full_name='deepf1.twenty_eighteen.protobuf.CarMotionData.m_roll', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=519,
)

DESCRIPTOR.message_types_by_name['CarMotionData'] = _CARMOTIONDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CarMotionData = _reflection.GeneratedProtocolMessageType('CarMotionData', (_message.Message,), {
  'DESCRIPTOR' : _CARMOTIONDATA,
  '__module__' : 'CarMotionData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.CarMotionData)
  })
_sym_db.RegisterMessage(CarMotionData)


# @@protoc_insertion_point(module_scope)
