# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChannelOrder_pb2 as ChannelOrder__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Image.proto',
  package='deepf1.protobuf.images',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bImage.proto\x12\x16\x64\x65\x65pf1.protobuf.images\x1a\x12\x43hannelOrder.proto\"t\n\x05Image\x12;\n\rchannel_order\x18\x01 \x01(\x0e\x32$.deepf1.protobuf.images.ChannelOrder\x12\x0c\n\x04rows\x18\x02 \x01(\x04\x12\x0c\n\x04\x63ols\x18\x03 \x01(\x04\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[ChannelOrder__pb2.DESCRIPTOR,])




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='deepf1.protobuf.images.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_order', full_name='deepf1.protobuf.images.Image.channel_order', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rows', full_name='deepf1.protobuf.images.Image.rows', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cols', full_name='deepf1.protobuf.images.Image.cols', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='deepf1.protobuf.images.Image.image_data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=175,
)

_IMAGE.fields_by_name['channel_order'].enum_type = ChannelOrder__pb2._CHANNELORDER
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.protobuf.images.Image)
  })
_sym_db.RegisterMessage(Image)


# @@protoc_insertion_point(module_scope)
