# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PacketEventData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PacketHeader_pb2 as PacketHeader__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PacketEventData.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15PacketEventData.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\x1a\x12PacketHeader.proto\"m\n\x0fPacketEventData\x12?\n\x08m_header\x18\x01 \x01(\x0b\x32-.deepf1.twenty_eighteen.protobuf.PacketHeader\x12\x19\n\x11m_eventStringCode\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[PacketHeader__pb2.DESCRIPTOR,])




_PACKETEVENTDATA = _descriptor.Descriptor(
  name='PacketEventData',
  full_name='deepf1.twenty_eighteen.protobuf.PacketEventData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_header', full_name='deepf1.twenty_eighteen.protobuf.PacketEventData.m_header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_eventStringCode', full_name='deepf1.twenty_eighteen.protobuf.PacketEventData.m_eventStringCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=187,
)

_PACKETEVENTDATA.fields_by_name['m_header'].message_type = PacketHeader__pb2._PACKETHEADER
DESCRIPTOR.message_types_by_name['PacketEventData'] = _PACKETEVENTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketEventData = _reflection.GeneratedProtocolMessageType('PacketEventData', (_message.Message,), {
  'DESCRIPTOR' : _PACKETEVENTDATA,
  '__module__' : 'PacketEventData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.PacketEventData)
  })
_sym_db.RegisterMessage(PacketEventData)


# @@protoc_insertion_point(module_scope)
