# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PacketSessionData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PacketHeader_pb2 as PacketHeader__pb2
import MarshalZone_pb2 as MarshalZone__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PacketSessionData.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17PacketSessionData.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\x1a\x12PacketHeader.proto\x1a\x11MarshalZone.proto\"\xce\x04\n\x11PacketSessionData\x12?\n\x08m_header\x18\x01 \x01(\x0b\x32-.deepf1.twenty_eighteen.protobuf.PacketHeader\x12\x11\n\tm_weather\x18\x02 \x01(\r\x12\x1a\n\x12m_trackTemperature\x18\x03 \x01(\x11\x12\x18\n\x10m_airTemperature\x18\x04 \x01(\x11\x12\x13\n\x0bm_totalLaps\x18\x05 \x01(\r\x12\x15\n\rm_trackLength\x18\x06 \x01(\r\x12\x15\n\rm_sessionType\x18\x07 \x01(\r\x12\x11\n\tm_trackId\x18\x08 \x01(\x11\x12\r\n\x05m_era\x18\t \x01(\r\x12\x19\n\x11m_sessionTimeLeft\x18\n \x01(\r\x12\x19\n\x11m_sessionDuration\x18\x0b \x01(\r\x12\x17\n\x0fm_pitSpeedLimit\x18\x0c \x01(\r\x12\x14\n\x0cm_gamePaused\x18\r \x01(\r\x12\x16\n\x0em_isSpectating\x18\x0e \x01(\r\x12\x1b\n\x13m_spectatorCarIndex\x18\x0f \x01(\r\x12\x1d\n\x15m_sliProNativeSupport\x18\x10 \x01(\r\x12\x19\n\x11m_numMarshalZones\x18\x11 \x01(\r\x12\x44\n\x0em_marshalZones\x18\x12 \x03(\x0b\x32,.deepf1.twenty_eighteen.protobuf.MarshalZone\x12\x19\n\x11m_safetyCarStatus\x18\x13 \x01(\r\x12\x15\n\rm_networkGame\x18\x14 \x01(\rb\x06proto3')
  ,
  dependencies=[PacketHeader__pb2.DESCRIPTOR,MarshalZone__pb2.DESCRIPTOR,])




_PACKETSESSIONDATA = _descriptor.Descriptor(
  name='PacketSessionData',
  full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_header', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_weather', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_weather', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_trackTemperature', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_trackTemperature', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_airTemperature', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_airTemperature', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_totalLaps', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_totalLaps', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_trackLength', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_trackLength', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_sessionType', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_sessionType', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_trackId', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_trackId', index=7,
      number=8, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_era', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_era', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_sessionTimeLeft', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_sessionTimeLeft', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_sessionDuration', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_sessionDuration', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_pitSpeedLimit', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_pitSpeedLimit', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_gamePaused', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_gamePaused', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_isSpectating', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_isSpectating', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_spectatorCarIndex', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_spectatorCarIndex', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_sliProNativeSupport', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_sliProNativeSupport', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_numMarshalZones', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_numMarshalZones', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_marshalZones', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_marshalZones', index=17,
      number=18, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_safetyCarStatus', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_safetyCarStatus', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_networkGame', full_name='deepf1.twenty_eighteen.protobuf.PacketSessionData.m_networkGame', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=690,
)

_PACKETSESSIONDATA.fields_by_name['m_header'].message_type = PacketHeader__pb2._PACKETHEADER
_PACKETSESSIONDATA.fields_by_name['m_marshalZones'].message_type = MarshalZone__pb2._MARSHALZONE
DESCRIPTOR.message_types_by_name['PacketSessionData'] = _PACKETSESSIONDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketSessionData = _reflection.GeneratedProtocolMessageType('PacketSessionData', (_message.Message,), {
  'DESCRIPTOR' : _PACKETSESSIONDATA,
  '__module__' : 'PacketSessionData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.PacketSessionData)
  })
_sym_db.RegisterMessage(PacketSessionData)


# @@protoc_insertion_point(module_scope)
