# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ParticipantData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ParticipantData.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15ParticipantData.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\"\x8c\x01\n\x0fParticipantData\x12\x16\n\x0em_aiControlled\x18\x01 \x01(\r\x12\x12\n\nm_driverId\x18\x02 \x01(\r\x12\x10\n\x08m_teamId\x18\x03 \x01(\r\x12\x14\n\x0cm_raceNumber\x18\x04 \x01(\r\x12\x15\n\rm_nationality\x18\x05 \x01(\r\x12\x0e\n\x06m_name\x18\x06 \x01(\tb\x06proto3')
)




_PARTICIPANTDATA = _descriptor.Descriptor(
  name='ParticipantData',
  full_name='deepf1.twenty_eighteen.protobuf.ParticipantData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_aiControlled', full_name='deepf1.twenty_eighteen.protobuf.ParticipantData.m_aiControlled', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_driverId', full_name='deepf1.twenty_eighteen.protobuf.ParticipantData.m_driverId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_teamId', full_name='deepf1.twenty_eighteen.protobuf.ParticipantData.m_teamId', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_raceNumber', full_name='deepf1.twenty_eighteen.protobuf.ParticipantData.m_raceNumber', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_nationality', full_name='deepf1.twenty_eighteen.protobuf.ParticipantData.m_nationality', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_name', full_name='deepf1.twenty_eighteen.protobuf.ParticipantData.m_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=199,
)

DESCRIPTOR.message_types_by_name['ParticipantData'] = _PARTICIPANTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParticipantData = _reflection.GeneratedProtocolMessageType('ParticipantData', (_message.Message,), {
  'DESCRIPTOR' : _PARTICIPANTDATA,
  '__module__' : 'ParticipantData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.ParticipantData)
  })
_sym_db.RegisterMessage(ParticipantData)


# @@protoc_insertion_point(module_scope)
