/* deepf1Stub.h
   Generated by gSOAP 2.8.61 for .\cpu_times.hpp

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/


#ifndef deepf1Stub_H
#define deepf1Stub_H
#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#include "stdsoap2.h"
#if GSOAP_VERSION != 20861
# error "GSOAP VERSION 20861 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


namespace deepf1 {

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

struct cpu_times;	/* .\cpu_times.hpp:5 */

/* .\cpu_times.hpp:5 */
#ifndef SOAP_TYPE_deepf1_cpu_times
#define SOAP_TYPE_deepf1_cpu_times (-7)
/* complex XSD type 'cpu-times': */
struct SOAP_CMAC cpu_times {
      public:
        /** Required element 'wall' of XSD type 'xsd:long' */
        long wall;
        /** Required element 'user' of XSD type 'xsd:long' */
        long user;
        /** Required element 'system' of XSD type 'xsd:long' */
        long system;
      public:
        /** Return unique type id SOAP_TYPE_deepf1_cpu_times */
        long soap_type() const { return SOAP_TYPE_deepf1_cpu_times; }
        /** Constructor with member initializations */
        cpu_times() : wall(), user(), system() { }
        /** Friend allocator */
        friend SOAP_FMAC1 cpu_times * SOAP_FMAC2 soap_instantiate_cpu_times(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* .\cpu_times.hpp:13 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_deepf1_SOAP_ENV__Header
#define SOAP_TYPE_deepf1_SOAP_ENV__Header (-1263628288)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_deepf1_SOAP_ENV__Header */
        long soap_type() const { return SOAP_TYPE_deepf1_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* .\cpu_times.hpp:13 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_deepf1_SOAP_ENV__Code
#define SOAP_TYPE_deepf1_SOAP_ENV__Code (-1263628289)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_deepf1_SOAP_ENV__Code */
        long soap_type() const { return SOAP_TYPE_deepf1_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code() : SOAP_ENV__Value(), SOAP_ENV__Subcode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* .\cpu_times.hpp:13 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_deepf1_SOAP_ENV__Detail
#define SOAP_TYPE_deepf1_SOAP_ENV__Detail (-1263628291)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_deepf1_SOAP_ENV__Detail */
        long soap_type() const { return SOAP_TYPE_deepf1_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail() : __any(), __type(), fault() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* .\cpu_times.hpp:13 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_deepf1_SOAP_ENV__Reason
#define SOAP_TYPE_deepf1_SOAP_ENV__Reason (-1263628294)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_deepf1_SOAP_ENV__Reason */
        long soap_type() const { return SOAP_TYPE_deepf1_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason() : SOAP_ENV__Text() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* .\cpu_times.hpp:13 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_deepf1_SOAP_ENV__Fault
#define SOAP_TYPE_deepf1_SOAP_ENV__Fault (-1263628295)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_deepf1_SOAP_ENV__Fault */
        long soap_type() const { return SOAP_TYPE_deepf1_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault() : faultcode(), faultstring(), faultactor(), detail(), SOAP_ENV__Code(), SOAP_ENV__Reason(), SOAP_ENV__Node(), SOAP_ENV__Role(), SOAP_ENV__Detail() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE_deepf1__XML
#define SOAP_TYPE_deepf1__XML (-5)

typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE_deepf1__QName
#define SOAP_TYPE_deepf1__QName (-6)

typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_deepf1_byte
#define SOAP_TYPE_deepf1_byte (-3)

#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_deepf1_int
#define SOAP_TYPE_deepf1_int (-1)

#endif

/* long has binding name 'long' for type 'xsd:long' */
#ifndef SOAP_TYPE_deepf1_long
#define SOAP_TYPE_deepf1_long (-8)

#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_deepf1_SOAP_ENV__Fault
#define SOAP_TYPE_deepf1_SOAP_ENV__Fault (-1263628295)

#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_deepf1_SOAP_ENV__Reason
#define SOAP_TYPE_deepf1_SOAP_ENV__Reason (-1263628294)

#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_deepf1_SOAP_ENV__Detail
#define SOAP_TYPE_deepf1_SOAP_ENV__Detail (-1263628291)

#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_deepf1_SOAP_ENV__Code
#define SOAP_TYPE_deepf1_SOAP_ENV__Code (-1263628289)

#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_deepf1_SOAP_ENV__Header
#define SOAP_TYPE_deepf1_SOAP_ENV__Header (-1263628288)

#endif

/* struct cpu_times has binding name 'cpu_times' for type 'cpu-times' */
#ifndef SOAP_TYPE_deepf1_cpu_times
#define SOAP_TYPE_deepf1_cpu_times (-7)

#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_deepf1_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_deepf1_PointerToSOAP_ENV__Reason (-1263628297)

#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_deepf1_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_deepf1_PointerToSOAP_ENV__Detail (-1263628296)

#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_deepf1_PointerToSOAP_ENV__Code
#define SOAP_TYPE_deepf1_PointerToSOAP_ENV__Code (-1263628290)

#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE_deepf1__QName
#define SOAP_TYPE_deepf1__QName (-6)

#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE_deepf1__XML
#define SOAP_TYPE_deepf1__XML (-5)

#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_deepf1_string
#define SOAP_TYPE_deepf1_string (-4)

#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


} // namespace deepf1


#endif

/* End of deepf1Stub.h */
