#!/bin/bash
#SBATCH --job-name="Deepracing Train AdmiralNet Pose Predictor"
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ttw2xk@virginia.edu
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
source /etc/profile.d/modules.sh
. ~/common_init
. ~/cuda_init
cd $DEEPRACINGDIR
cd deepracing
. ./data-logger/build/addpythonpath
echo $PYTHONPATH
cd DCNN-Pytorch
cd deepracing_models
echo "Running command: python3 main_pose_predictor.py $@"
python3 main_pose_predictor.py $@