geometry_msgs/PointStamped world_position
geometry_msgs/Vector3Stamped world_velocity
geometry_msgs/Vector3Stamped world_forward_dir
geometry_msgs/Vector3Stamped  world_right_dir
geometry_msgs/Vector3Stamped  world_up_dir
float32 g_force_lateral# Lateral G-force component
float32 g_force_longitudinal# Longitudinal G-force component
float32 g_force_vertical# Vertical G-force component
float32 yaw# yaw angle in radians
float32 pitch# Pitch angle in radians
float32 roll# Roll angle in radians