uint8 front_wing # Front wing aero
uint8 rear_wing # Rear wing aero
uint8 on_throttle # Differential adjustment on throttle (percentage)
uint8 off_throttle # Differential adjustment off throttle (percentage)
float32 front_camber # Front camber angle (suspension geometry)
float32 rear_camber # Rear camber angle (suspension geometry)
float32 front_toe # Front toe angle (suspension geometry)
float32 rear_toe # Rear toe angle (suspension geometry)
uint8 front_suspension # Front suspension
uint8 rear_suspension # Rear suspension
uint8 front_anti_roll_bar # Front anti-roll bar
uint8 rear_anti_roll_bar # Front anti-roll bar
uint8 front_suspension_height # Front ride height
uint8 rear_suspension_height # Rear ride height
uint8 brake_pressure # Brake pressure (percentage)
uint8 brake_bias # Brake bias (percentage)
float32 front_tyre_pressure # Front tyre pressure (PSI)
float32 rear_tyre_pressure # Rear tyre pressure (PSI)
uint8 ballast # Ballast
float32 fuel_load # Fuel load