search_string: "cmake"
track_name: "Australia"
driver_name: "Trent"
images_folder: "images"
udp_folder: "udp_data"
udp_threads: 1
image_threads: 6 
image_capture_frequency: 60.0
initial_delay_time: 1.0
