# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CarTelemetryData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CarTelemetryData.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x43\x61rTelemetryData.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\"\xd2\x02\n\x10\x43\x61rTelemetryData\x12\x0f\n\x07m_speed\x18\x01 \x01(\r\x12\x12\n\nm_throttle\x18\x02 \x01(\r\x12\x0f\n\x07m_steer\x18\x03 \x01(\x11\x12\x0f\n\x07m_brake\x18\x04 \x01(\r\x12\x10\n\x08m_clutch\x18\x05 \x01(\r\x12\x0e\n\x06m_gear\x18\x06 \x01(\x11\x12\x13\n\x0bm_engineRPM\x18\x07 \x01(\r\x12\r\n\x05m_drs\x18\x08 \x01(\r\x12\x1a\n\x12m_revLightsPercent\x18\t \x01(\r\x12\x1b\n\x13m_brakesTemperature\x18\n \x03(\r\x12!\n\x19m_tyresSurfaceTemperature\x18\x0b \x03(\r\x12\x1f\n\x17m_tyresInnerTemperature\x18\x0c \x03(\r\x12\x1b\n\x13m_engineTemperature\x18\r \x01(\r\x12\x17\n\x0fm_tyresPressure\x18\x0e \x03(\x02\x62\x06proto3')
)




_CARTELEMETRYDATA = _descriptor.Descriptor(
  name='CarTelemetryData',
  full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_speed', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_speed', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_throttle', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_throttle', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_steer', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_steer', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_brake', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_brake', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_clutch', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_clutch', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_gear', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_gear', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_engineRPM', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_engineRPM', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_drs', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_drs', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_revLightsPercent', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_revLightsPercent', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_brakesTemperature', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_brakesTemperature', index=9,
      number=10, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_tyresSurfaceTemperature', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_tyresSurfaceTemperature', index=10,
      number=11, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_tyresInnerTemperature', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_tyresInnerTemperature', index=11,
      number=12, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_engineTemperature', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_engineTemperature', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_tyresPressure', full_name='deepf1.twenty_eighteen.protobuf.CarTelemetryData.m_tyresPressure', index=13,
      number=14, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=398,
)

DESCRIPTOR.message_types_by_name['CarTelemetryData'] = _CARTELEMETRYDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CarTelemetryData = _reflection.GeneratedProtocolMessageType('CarTelemetryData', (_message.Message,), {
  'DESCRIPTOR' : _CARTELEMETRYDATA,
  '__module__' : 'CarTelemetryData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.CarTelemetryData)
  })
_sym_db.RegisterMessage(CarTelemetryData)


# @@protoc_insertion_point(module_scope)
