# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CarUDPData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CarUDPData.proto',
  package='deepf1.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x43\x61rUDPData.proto\x12\x0f\x64\x65\x65pf1.protobuf\"\xf6\x02\n\nCarUDPData\x12\x17\n\x0fm_worldPosition\x18\x01 \x03(\x02\x12\x15\n\rm_lastLapTime\x18\x02 \x01(\x02\x12\x18\n\x10m_currentLapTime\x18\x03 \x01(\x02\x12\x15\n\rm_bestLapTime\x18\x04 \x01(\x02\x12\x15\n\rm_sector1Time\x18\x05 \x01(\x02\x12\x15\n\rm_sector2Time\x18\x06 \x01(\x02\x12\x15\n\rm_lapDistance\x18\x07 \x01(\x02\x12\x12\n\nm_driverId\x18\x08 \x01(\r\x12\x10\n\x08m_teamId\x18\t \x01(\r\x12\x15\n\rm_carPosition\x18\n \x01(\r\x12\x17\n\x0fm_currentLapNum\x18\x0b \x01(\r\x12\x16\n\x0em_tyreCompound\x18\x0c \x01(\r\x12\x10\n\x08m_inPits\x18\r \x01(\r\x12\x10\n\x08m_sector\x18\x0e \x01(\r\x12\x1b\n\x13m_currentLapInvalid\x18\x0f \x01(\r\x12\x13\n\x0bm_penalties\x18\x10 \x01(\rb\x06proto3')
)




_CARUDPDATA = _descriptor.Descriptor(
  name='CarUDPData',
  full_name='deepf1.protobuf.CarUDPData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_worldPosition', full_name='deepf1.protobuf.CarUDPData.m_worldPosition', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_lastLapTime', full_name='deepf1.protobuf.CarUDPData.m_lastLapTime', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_currentLapTime', full_name='deepf1.protobuf.CarUDPData.m_currentLapTime', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_bestLapTime', full_name='deepf1.protobuf.CarUDPData.m_bestLapTime', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_sector1Time', full_name='deepf1.protobuf.CarUDPData.m_sector1Time', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_sector2Time', full_name='deepf1.protobuf.CarUDPData.m_sector2Time', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_lapDistance', full_name='deepf1.protobuf.CarUDPData.m_lapDistance', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_driverId', full_name='deepf1.protobuf.CarUDPData.m_driverId', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_teamId', full_name='deepf1.protobuf.CarUDPData.m_teamId', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_carPosition', full_name='deepf1.protobuf.CarUDPData.m_carPosition', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_currentLapNum', full_name='deepf1.protobuf.CarUDPData.m_currentLapNum', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_tyreCompound', full_name='deepf1.protobuf.CarUDPData.m_tyreCompound', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_inPits', full_name='deepf1.protobuf.CarUDPData.m_inPits', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_sector', full_name='deepf1.protobuf.CarUDPData.m_sector', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_currentLapInvalid', full_name='deepf1.protobuf.CarUDPData.m_currentLapInvalid', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_penalties', full_name='deepf1.protobuf.CarUDPData.m_penalties', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=412,
)

DESCRIPTOR.message_types_by_name['CarUDPData'] = _CARUDPDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CarUDPData = _reflection.GeneratedProtocolMessageType('CarUDPData', (_message.Message,), dict(
  DESCRIPTOR = _CARUDPDATA,
  __module__ = 'CarUDPData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.protobuf.CarUDPData)
  ))
_sym_db.RegisterMessage(CarUDPData)


# @@protoc_insertion_point(module_scope)
