# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelOrder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ChannelOrder.proto',
  package='deepf1.protobuf.images',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x43hannelOrder.proto\x12\x16\x64\x65\x65pf1.protobuf.images*C\n\x0c\x43hannelOrder\x12\r\n\tGRAYSCALE\x10\x00\x12\x07\n\x03\x42GR\x10\x01\x12\x07\n\x03RGB\x10\x02\x12\x08\n\x04\x42GRA\x10\x03\x12\x08\n\x04RGBA\x10\x04\x62\x06proto3')
)

_CHANNELORDER = _descriptor.EnumDescriptor(
  name='ChannelOrder',
  full_name='deepf1.protobuf.images.ChannelOrder',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GRAYSCALE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGRA', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGBA', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=46,
  serialized_end=113,
)
_sym_db.RegisterEnumDescriptor(_CHANNELORDER)

ChannelOrder = enum_type_wrapper.EnumTypeWrapper(_CHANNELORDER)
GRAYSCALE = 0
BGR = 1
RGB = 2
BGRA = 3
RGBA = 4


DESCRIPTOR.enum_types_by_name['ChannelOrder'] = _CHANNELORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
