# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FrameId.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FrameId.proto',
  package='deepf1.protobuf.eigen',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rFrameId.proto\x12\x15\x64\x65\x65pf1.protobuf.eigen* \n\x07\x46rameId\x12\n\n\x06GLOBAL\x10\x00\x12\t\n\x05LOCAL\x10\x01\x62\x06proto3')
)

_FRAMEID = _descriptor.EnumDescriptor(
  name='FrameId',
  full_name='deepf1.protobuf.eigen.FrameId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GLOBAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCAL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=40,
  serialized_end=72,
)
_sym_db.RegisterEnumDescriptor(_FRAMEID)

FrameId = enum_type_wrapper.EnumTypeWrapper(_FRAMEID)
GLOBAL = 0
LOCAL = 1


DESCRIPTOR.enum_types_by_name['FrameId'] = _FRAMEID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
