# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageLabel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ImageLabel.proto',
  package='deepf1.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x10ImageLabel.proto\x12\x0f\x64\x65\x65pf1.protobuf\"?\n\nImageLabel\x12\x10\n\x08steering\x18\x01 \x01(\x02\x12\x10\n\x08throttle\x18\x02 \x01(\x02\x12\r\n\x05\x62rake\x18\x03 \x01(\x02\x62\x06proto3')
)




_IMAGELABEL = _descriptor.Descriptor(
  name='ImageLabel',
  full_name='deepf1.protobuf.ImageLabel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steering', full_name='deepf1.protobuf.ImageLabel.steering', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throttle', full_name='deepf1.protobuf.ImageLabel.throttle', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brake', full_name='deepf1.protobuf.ImageLabel.brake', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['ImageLabel'] = _IMAGELABEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageLabel = _reflection.GeneratedProtocolMessageType('ImageLabel', (_message.Message,), dict(
  DESCRIPTOR = _IMAGELABEL,
  __module__ = 'ImageLabel_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.protobuf.ImageLabel)
  ))
_sym_db.RegisterMessage(ImageLabel)


# @@protoc_insertion_point(module_scope)
