# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LabeledImage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ImageLabel_pb2 as ImageLabel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LabeledImage.proto',
  package='deepf1.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12LabeledImage.proto\x12\x0f\x64\x65\x65pf1.protobuf\x1a\x10ImageLabel.proto\"N\n\x0cLabeledImage\x12\x12\n\nimage_file\x18\x01 \x01(\t\x12*\n\x05label\x18\x02 \x01(\x0b\x32\x1b.deepf1.protobuf.ImageLabelb\x06proto3')
  ,
  dependencies=[ImageLabel__pb2.DESCRIPTOR,])




_LABELEDIMAGE = _descriptor.Descriptor(
  name='LabeledImage',
  full_name='deepf1.protobuf.LabeledImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_file', full_name='deepf1.protobuf.LabeledImage.image_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='deepf1.protobuf.LabeledImage.label', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=135,
)

_LABELEDIMAGE.fields_by_name['label'].message_type = ImageLabel__pb2._IMAGELABEL
DESCRIPTOR.message_types_by_name['LabeledImage'] = _LABELEDIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LabeledImage = _reflection.GeneratedProtocolMessageType('LabeledImage', (_message.Message,), {
  'DESCRIPTOR' : _LABELEDIMAGE,
  '__module__' : 'LabeledImage_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.protobuf.LabeledImage)
  })
_sym_db.RegisterMessage(LabeledImage)


# @@protoc_insertion_point(module_scope)
