# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MarshalZone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MarshalZone.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11MarshalZone.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\"6\n\x0bMarshalZone\x12\x13\n\x0bm_zoneStart\x18\x01 \x01(\x02\x12\x12\n\nm_zoneFlag\x18\x02 \x01(\x05\x62\x06proto3')
)




_MARSHALZONE = _descriptor.Descriptor(
  name='MarshalZone',
  full_name='deepf1.twenty_eighteen.protobuf.MarshalZone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_zoneStart', full_name='deepf1.twenty_eighteen.protobuf.MarshalZone.m_zoneStart', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_zoneFlag', full_name='deepf1.twenty_eighteen.protobuf.MarshalZone.m_zoneFlag', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['MarshalZone'] = _MARSHALZONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MarshalZone = _reflection.GeneratedProtocolMessageType('MarshalZone', (_message.Message,), {
  'DESCRIPTOR' : _MARSHALZONE,
  '__module__' : 'MarshalZone_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.MarshalZone)
  })
_sym_db.RegisterMessage(MarshalZone)


# @@protoc_insertion_point(module_scope)
