# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PacketCarStatusData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PacketHeader_pb2 as PacketHeader__pb2
import CarStatusData_pb2 as CarStatusData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PacketCarStatusData.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19PacketCarStatusData.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\x1a\x12PacketHeader.proto\x1a\x13\x43\x61rStatusData.proto\"\x9f\x01\n\x13PacketCarStatusData\x12?\n\x08m_header\x18\x01 \x01(\x0b\x32-.deepf1.twenty_eighteen.protobuf.PacketHeader\x12G\n\x0fm_carStatusData\x18\x02 \x03(\x0b\x32..deepf1.twenty_eighteen.protobuf.CarStatusDatab\x06proto3')
  ,
  dependencies=[PacketHeader__pb2.DESCRIPTOR,CarStatusData__pb2.DESCRIPTOR,])




_PACKETCARSTATUSDATA = _descriptor.Descriptor(
  name='PacketCarStatusData',
  full_name='deepf1.twenty_eighteen.protobuf.PacketCarStatusData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_header', full_name='deepf1.twenty_eighteen.protobuf.PacketCarStatusData.m_header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_carStatusData', full_name='deepf1.twenty_eighteen.protobuf.PacketCarStatusData.m_carStatusData', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=263,
)

_PACKETCARSTATUSDATA.fields_by_name['m_header'].message_type = PacketHeader__pb2._PACKETHEADER
_PACKETCARSTATUSDATA.fields_by_name['m_carStatusData'].message_type = CarStatusData__pb2._CARSTATUSDATA
DESCRIPTOR.message_types_by_name['PacketCarStatusData'] = _PACKETCARSTATUSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketCarStatusData = _reflection.GeneratedProtocolMessageType('PacketCarStatusData', (_message.Message,), {
  'DESCRIPTOR' : _PACKETCARSTATUSDATA,
  '__module__' : 'PacketCarStatusData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.PacketCarStatusData)
  })
_sym_db.RegisterMessage(PacketCarStatusData)


# @@protoc_insertion_point(module_scope)
