# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PacketParticipantsData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PacketHeader_pb2 as PacketHeader__pb2
import ParticipantData_pb2 as ParticipantData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PacketParticipantsData.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cPacketParticipantsData.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\x1a\x12PacketHeader.proto\x1a\x15ParticipantData.proto\"\xb6\x01\n\x16PacketParticipantsData\x12?\n\x08m_header\x18\x01 \x01(\x0b\x32-.deepf1.twenty_eighteen.protobuf.PacketHeader\x12\x11\n\tm_numCars\x18\x02 \x01(\r\x12H\n\x0em_participants\x18\x03 \x03(\x0b\x32\x30.deepf1.twenty_eighteen.protobuf.ParticipantDatab\x06proto3')
  ,
  dependencies=[PacketHeader__pb2.DESCRIPTOR,ParticipantData__pb2.DESCRIPTOR,])




_PACKETPARTICIPANTSDATA = _descriptor.Descriptor(
  name='PacketParticipantsData',
  full_name='deepf1.twenty_eighteen.protobuf.PacketParticipantsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_header', full_name='deepf1.twenty_eighteen.protobuf.PacketParticipantsData.m_header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_numCars', full_name='deepf1.twenty_eighteen.protobuf.PacketParticipantsData.m_numCars', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_participants', full_name='deepf1.twenty_eighteen.protobuf.PacketParticipantsData.m_participants', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=291,
)

_PACKETPARTICIPANTSDATA.fields_by_name['m_header'].message_type = PacketHeader__pb2._PACKETHEADER
_PACKETPARTICIPANTSDATA.fields_by_name['m_participants'].message_type = ParticipantData__pb2._PARTICIPANTDATA
DESCRIPTOR.message_types_by_name['PacketParticipantsData'] = _PACKETPARTICIPANTSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketParticipantsData = _reflection.GeneratedProtocolMessageType('PacketParticipantsData', (_message.Message,), {
  'DESCRIPTOR' : _PACKETPARTICIPANTSDATA,
  '__module__' : 'PacketParticipantsData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.PacketParticipantsData)
  })
_sym_db.RegisterMessage(PacketParticipantsData)


# @@protoc_insertion_point(module_scope)
