# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PacketMotionData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PacketHeader_pb2 as PacketHeader__pb2
import CarMotionData_pb2 as CarMotionData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PacketMotionData.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16PacketMotionData.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\x1a\x12PacketHeader.proto\x1a\x13\x43\x61rMotionData.proto\"\xc3\x04\n\x10PacketMotionData\x12?\n\x08m_header\x18\x01 \x01(\x0b\x32-.deepf1.twenty_eighteen.protobuf.PacketHeader\x12G\n\x0fm_carMotionData\x18\x02 \x03(\x0b\x32..deepf1.twenty_eighteen.protobuf.CarMotionData\x12\x1c\n\x14m_suspensionPosition\x18\x03 \x03(\x02\x12\x1c\n\x14m_suspensionVelocity\x18\x04 \x03(\x02\x12 \n\x18m_suspensionAcceleration\x18\x05 \x03(\x02\x12\x14\n\x0cm_wheelSpeed\x18\x06 \x03(\x02\x12\x13\n\x0bm_wheelSlip\x18\x07 \x03(\x02\x12\x18\n\x10m_localVelocityX\x18\x08 \x01(\x02\x12\x18\n\x10m_localVelocityY\x18\t \x01(\x02\x12\x18\n\x10m_localVelocityZ\x18\n \x01(\x02\x12\x1a\n\x12m_angularVelocityX\x18\x0b \x01(\x02\x12\x1a\n\x12m_angularVelocityY\x18\x0c \x01(\x02\x12\x1a\n\x12m_angularVelocityZ\x18\r \x01(\x02\x12\x1e\n\x16m_angularAccelerationX\x18\x0e \x01(\x02\x12\x1e\n\x16m_angularAccelerationY\x18\x0f \x01(\x02\x12\x1e\n\x16m_angularAccelerationZ\x18\x10 \x01(\x02\x12\x1a\n\x12m_frontWheelsAngle\x18\x11 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[PacketHeader__pb2.DESCRIPTOR,CarMotionData__pb2.DESCRIPTOR,])




_PACKETMOTIONDATA = _descriptor.Descriptor(
  name='PacketMotionData',
  full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_header', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_carMotionData', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_carMotionData', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_suspensionPosition', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_suspensionPosition', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_suspensionVelocity', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_suspensionVelocity', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_suspensionAcceleration', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_suspensionAcceleration', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_wheelSpeed', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_wheelSpeed', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_wheelSlip', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_wheelSlip', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_localVelocityX', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_localVelocityX', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_localVelocityY', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_localVelocityY', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_localVelocityZ', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_localVelocityZ', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_angularVelocityX', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_angularVelocityX', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_angularVelocityY', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_angularVelocityY', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_angularVelocityZ', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_angularVelocityZ', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_angularAccelerationX', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_angularAccelerationX', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_angularAccelerationY', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_angularAccelerationY', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_angularAccelerationZ', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_angularAccelerationZ', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_frontWheelsAngle', full_name='deepf1.twenty_eighteen.protobuf.PacketMotionData.m_frontWheelsAngle', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=680,
)

_PACKETMOTIONDATA.fields_by_name['m_header'].message_type = PacketHeader__pb2._PACKETHEADER
_PACKETMOTIONDATA.fields_by_name['m_carMotionData'].message_type = CarMotionData__pb2._CARMOTIONDATA
DESCRIPTOR.message_types_by_name['PacketMotionData'] = _PACKETMOTIONDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketMotionData = _reflection.GeneratedProtocolMessageType('PacketMotionData', (_message.Message,), {
  'DESCRIPTOR' : _PACKETMOTIONDATA,
  '__module__' : 'PacketMotionData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.PacketMotionData)
  })
_sym_db.RegisterMessage(PacketMotionData)


# @@protoc_insertion_point(module_scope)
