# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PacketLapData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PacketHeader_pb2 as PacketHeader__pb2
import LapData_pb2 as LapData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PacketLapData.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13PacketLapData.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\x1a\x12PacketHeader.proto\x1a\rLapData.proto\"\x8d\x01\n\rPacketLapData\x12?\n\x08m_header\x18\x01 \x01(\x0b\x32-.deepf1.twenty_eighteen.protobuf.PacketHeader\x12;\n\tm_lapData\x18\x02 \x03(\x0b\x32(.deepf1.twenty_eighteen.protobuf.LapDatab\x06proto3')
  ,
  dependencies=[PacketHeader__pb2.DESCRIPTOR,LapData__pb2.DESCRIPTOR,])




_PACKETLAPDATA = _descriptor.Descriptor(
  name='PacketLapData',
  full_name='deepf1.twenty_eighteen.protobuf.PacketLapData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_header', full_name='deepf1.twenty_eighteen.protobuf.PacketLapData.m_header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_lapData', full_name='deepf1.twenty_eighteen.protobuf.PacketLapData.m_lapData', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=233,
)

_PACKETLAPDATA.fields_by_name['m_header'].message_type = PacketHeader__pb2._PACKETHEADER
_PACKETLAPDATA.fields_by_name['m_lapData'].message_type = LapData__pb2._LAPDATA
DESCRIPTOR.message_types_by_name['PacketLapData'] = _PACKETLAPDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketLapData = _reflection.GeneratedProtocolMessageType('PacketLapData', (_message.Message,), {
  'DESCRIPTOR' : _PACKETLAPDATA,
  '__module__' : 'PacketLapData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.PacketLapData)
  })
_sym_db.RegisterMessage(PacketLapData)


# @@protoc_insertion_point(module_scope)
