# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Pose3d.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Quaterniond_pb2 as Quaterniond__pb2
import Vector3d_pb2 as Vector3d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Pose3d.proto',
  package='deepf1.protobuf.eigen',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cPose3d.proto\x12\x15\x64\x65\x65pf1.protobuf.eigen\x1a\x11Quaterniond.proto\x1a\x0eVector3d.proto\"\x9c\x01\n\x06Pose3d\x12\x34\n\x0btranslation\x18\x01 \x01(\x0b\x32\x1f.deepf1.protobuf.eigen.Vector3d\x12\x34\n\x08rotation\x18\x02 \x01(\x0b\x32\".deepf1.protobuf.eigen.Quaterniond\x12\x14\n\x0csession_time\x18\x03 \x01(\x01\x12\x10\n\x08\x66rame_id\x18\x04 \x01(\tb\x06proto3')
  ,
  dependencies=[Quaterniond__pb2.DESCRIPTOR,Vector3d__pb2.DESCRIPTOR,])




_POSE3D = _descriptor.Descriptor(
  name='Pose3d',
  full_name='deepf1.protobuf.eigen.Pose3d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='deepf1.protobuf.eigen.Pose3d.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='deepf1.protobuf.eigen.Pose3d.rotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_time', full_name='deepf1.protobuf.eigen.Pose3d.session_time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='deepf1.protobuf.eigen.Pose3d.frame_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=231,
)

_POSE3D.fields_by_name['translation'].message_type = Vector3d__pb2._VECTOR3D
_POSE3D.fields_by_name['rotation'].message_type = Quaterniond__pb2._QUATERNIOND
DESCRIPTOR.message_types_by_name['Pose3d'] = _POSE3D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pose3d = _reflection.GeneratedProtocolMessageType('Pose3d', (_message.Message,), {
  'DESCRIPTOR' : _POSE3D,
  '__module__' : 'Pose3d_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.protobuf.eigen.Pose3d)
  })
_sym_db.RegisterMessage(Pose3d)


# @@protoc_insertion_point(module_scope)
