# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PoseSequenceLabel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector3dStamped_pb2 as Vector3dStamped__pb2
import Pose3d_pb2 as Pose3d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PoseSequenceLabel.proto',
  package='deepf1.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17PoseSequenceLabel.proto\x12\x0f\x64\x65\x65pf1.protobuf\x1a\x15Vector3dStamped.proto\x1a\x0cPose3d.proto\"\x96\x02\n\x11PoseSequenceLabel\x12\x12\n\nimage_file\x18\x01 \x01(\t\x12/\n\x08\x63\x61r_pose\x18\x02 \x01(\x0b\x32\x1d.deepf1.protobuf.eigen.Pose3d\x12<\n\x0c\x63\x61r_velocity\x18\x03 \x01(\x0b\x32&.deepf1.protobuf.eigen.Vector3dStamped\x12\x37\n\x10subsequent_poses\x18\x04 \x03(\x0b\x32\x1d.deepf1.protobuf.eigen.Pose3d\x12\x45\n\x15subsequent_velocities\x18\x05 \x03(\x0b\x32&.deepf1.protobuf.eigen.Vector3dStampedb\x06proto3')
  ,
  dependencies=[Vector3dStamped__pb2.DESCRIPTOR,Pose3d__pb2.DESCRIPTOR,])




_POSESEQUENCELABEL = _descriptor.Descriptor(
  name='PoseSequenceLabel',
  full_name='deepf1.protobuf.PoseSequenceLabel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_file', full_name='deepf1.protobuf.PoseSequenceLabel.image_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='car_pose', full_name='deepf1.protobuf.PoseSequenceLabel.car_pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='car_velocity', full_name='deepf1.protobuf.PoseSequenceLabel.car_velocity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subsequent_poses', full_name='deepf1.protobuf.PoseSequenceLabel.subsequent_poses', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subsequent_velocities', full_name='deepf1.protobuf.PoseSequenceLabel.subsequent_velocities', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=360,
)

_POSESEQUENCELABEL.fields_by_name['car_pose'].message_type = Pose3d__pb2._POSE3D
_POSESEQUENCELABEL.fields_by_name['car_velocity'].message_type = Vector3dStamped__pb2._VECTOR3DSTAMPED
_POSESEQUENCELABEL.fields_by_name['subsequent_poses'].message_type = Pose3d__pb2._POSE3D
_POSESEQUENCELABEL.fields_by_name['subsequent_velocities'].message_type = Vector3dStamped__pb2._VECTOR3DSTAMPED
DESCRIPTOR.message_types_by_name['PoseSequenceLabel'] = _POSESEQUENCELABEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PoseSequenceLabel = _reflection.GeneratedProtocolMessageType('PoseSequenceLabel', (_message.Message,), {
  'DESCRIPTOR' : _POSESEQUENCELABEL,
  '__module__' : 'PoseSequenceLabel_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.protobuf.PoseSequenceLabel)
  })
_sym_db.RegisterMessage(PoseSequenceLabel)


# @@protoc_insertion_point(module_scope)
