# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Quaterniond.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Quaterniond.proto',
  package='deepf1.protobuf.eigen',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11Quaterniond.proto\x12\x15\x64\x65\x65pf1.protobuf.eigen\"9\n\x0bQuaterniond\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\x62\x06proto3')
)




_QUATERNIOND = _descriptor.Descriptor(
  name='Quaterniond',
  full_name='deepf1.protobuf.eigen.Quaterniond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='deepf1.protobuf.eigen.Quaterniond.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='deepf1.protobuf.eigen.Quaterniond.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='deepf1.protobuf.eigen.Quaterniond.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='deepf1.protobuf.eigen.Quaterniond.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['Quaterniond'] = _QUATERNIOND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Quaterniond = _reflection.GeneratedProtocolMessageType('Quaterniond', (_message.Message,), {
  'DESCRIPTOR' : _QUATERNIOND,
  '__module__' : 'Quaterniond_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.protobuf.eigen.Quaterniond)
  })
_sym_db.RegisterMessage(Quaterniond)


# @@protoc_insertion_point(module_scope)
