# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TimestampedPacketSessionData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PacketSessionData_pb2 as PacketSessionData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TimestampedPacketSessionData.proto',
  package='deepf1.twenty_eighteen.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"TimestampedPacketSessionData.proto\x12\x1f\x64\x65\x65pf1.twenty_eighteen.protobuf\x1a\x17PacketSessionData.proto\"y\n\x1cTimestampedPacketSessionData\x12\x46\n\nudp_packet\x18\x01 \x01(\x0b\x32\x32.deepf1.twenty_eighteen.protobuf.PacketSessionData\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x62\x06proto3')
  ,
  dependencies=[PacketSessionData__pb2.DESCRIPTOR,])




_TIMESTAMPEDPACKETSESSIONDATA = _descriptor.Descriptor(
  name='TimestampedPacketSessionData',
  full_name='deepf1.twenty_eighteen.protobuf.TimestampedPacketSessionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='udp_packet', full_name='deepf1.twenty_eighteen.protobuf.TimestampedPacketSessionData.udp_packet', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='deepf1.twenty_eighteen.protobuf.TimestampedPacketSessionData.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=217,
)

_TIMESTAMPEDPACKETSESSIONDATA.fields_by_name['udp_packet'].message_type = PacketSessionData__pb2._PACKETSESSIONDATA
DESCRIPTOR.message_types_by_name['TimestampedPacketSessionData'] = _TIMESTAMPEDPACKETSESSIONDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimestampedPacketSessionData = _reflection.GeneratedProtocolMessageType('TimestampedPacketSessionData', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMPEDPACKETSESSIONDATA,
  '__module__' : 'TimestampedPacketSessionData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.twenty_eighteen.protobuf.TimestampedPacketSessionData)
  })
_sym_db.RegisterMessage(TimestampedPacketSessionData)


# @@protoc_insertion_point(module_scope)
