# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Vector3d.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Vector3d.proto',
  package='deepf1.protobuf.eigen',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eVector3d.proto\x12\x15\x64\x65\x65pf1.protobuf.eigen\"+\n\x08Vector3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x62\x06proto3')
)




_VECTOR3D = _descriptor.Descriptor(
  name='Vector3d',
  full_name='deepf1.protobuf.eigen.Vector3d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='deepf1.protobuf.eigen.Vector3d.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='deepf1.protobuf.eigen.Vector3d.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='deepf1.protobuf.eigen.Vector3d.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Vector3d'] = _VECTOR3D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3d = _reflection.GeneratedProtocolMessageType('Vector3d', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3D,
  '__module__' : 'Vector3d_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.protobuf.eigen.Vector3d)
  })
_sym_db.RegisterMessage(Vector3d)


# @@protoc_insertion_point(module_scope)
