# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Vector3dStamped.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector3d_pb2 as Vector3d__pb2
import FrameId_pb2 as FrameId__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Vector3dStamped.proto',
  package='deepf1.protobuf.eigen',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15Vector3dStamped.proto\x12\x15\x64\x65\x65pf1.protobuf.eigen\x1a\x0eVector3d.proto\x1a\rFrameId.proto\"\x87\x01\n\x0fVector3dStamped\x12/\n\x06vector\x18\x01 \x01(\x0b\x32\x1f.deepf1.protobuf.eigen.Vector3d\x12-\n\x05\x66rame\x18\x02 \x01(\x0e\x32\x1e.deepf1.protobuf.eigen.FrameId\x12\x14\n\x0csession_time\x18\x03 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[Vector3d__pb2.DESCRIPTOR,FrameId__pb2.DESCRIPTOR,])




_VECTOR3DSTAMPED = _descriptor.Descriptor(
  name='Vector3dStamped',
  full_name='deepf1.protobuf.eigen.Vector3dStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='deepf1.protobuf.eigen.Vector3dStamped.vector', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame', full_name='deepf1.protobuf.eigen.Vector3dStamped.frame', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_time', full_name='deepf1.protobuf.eigen.Vector3dStamped.session_time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=215,
)

_VECTOR3DSTAMPED.fields_by_name['vector'].message_type = Vector3d__pb2._VECTOR3D
_VECTOR3DSTAMPED.fields_by_name['frame'].enum_type = FrameId__pb2._FRAMEID
DESCRIPTOR.message_types_by_name['Vector3dStamped'] = _VECTOR3DSTAMPED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3dStamped = _reflection.GeneratedProtocolMessageType('Vector3dStamped', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3DSTAMPED,
  '__module__' : 'Vector3dStamped_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.protobuf.eigen.Vector3dStamped)
  })
_sym_db.RegisterMessage(Vector3dStamped)


# @@protoc_insertion_point(module_scope)
