# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TimestampedUDPData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UDPData_pb2 as UDPData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TimestampedUDPData.proto',
  package='deepf1.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x18TimestampedUDPData.proto\x12\x0f\x64\x65\x65pf1.protobuf\x1a\rUDPData.proto\"U\n\x12TimestampedUDPData\x12,\n\nudp_packet\x18\x01 \x01(\x0b\x32\x18.deepf1.protobuf.UDPData\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x62\x06proto3')
  ,
  dependencies=[UDPData__pb2.DESCRIPTOR,])




_TIMESTAMPEDUDPDATA = _descriptor.Descriptor(
  name='TimestampedUDPData',
  full_name='deepf1.protobuf.TimestampedUDPData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='udp_packet', full_name='deepf1.protobuf.TimestampedUDPData.udp_packet', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='deepf1.protobuf.TimestampedUDPData.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=145,
)

_TIMESTAMPEDUDPDATA.fields_by_name['udp_packet'].message_type = UDPData__pb2._UDPDATA
DESCRIPTOR.message_types_by_name['TimestampedUDPData'] = _TIMESTAMPEDUDPDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimestampedUDPData = _reflection.GeneratedProtocolMessageType('TimestampedUDPData', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMPEDUDPDATA,
  __module__ = 'TimestampedUDPData_pb2'
  # @@protoc_insertion_point(class_scope:deepf1.protobuf.TimestampedUDPData)
  ))
_sym_db.RegisterMessage(TimestampedUDPData)


# @@protoc_insertion_point(module_scope)
