float32 world_position_x# World space x position
float32 world_position_y# World space y position
float32 world_position_z# World space z position
float32 world_velocity_x# Velocity in world space x
float32 world_velocity_y# Velocity in world space y
float32 world_velocity_z# Velocity in world space z
int32 world_forward_dir_x# World space forward x direction (normalised)
int32 world_forward_dir_y# World space forward y direction (normalised)
int32 world_forward_dir_z# World space forward z direction (normalised)
int32 world_right_dir_x# World space right x direction (normalised)
int32 world_right_dir_y# World space right y direction (normalised)
int32 world_right_dir_z# World space right z direction (normalised)
float32 g_force_lateral# Lateral G-force component
float32 g_force_longitudinal# Longitudinal G-force component
float32 g_force_vertical# Vertical G-force component
float32 yaw# yaw angle in radians
float32 pitch# Pitch angle in radians
float32 roll# Roll angle in radians